[hints]
worktree_tip_dismissed = true

[cli]
installer = "internal"

[ui]
max_thoughts_width = 120
fork_secondary_model = "grok-build"
yolo = false
compact_mode = false
permission_mode = "always-approve"

[models]
default = "grok-composer-2.5-fast"

[marketplace]
official_marketplace_auto_installed = true
default_skills_installs_purged = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"

[plugins]
enabled = [
    "cloudflare",
    "ponytail",
]

[privacy]
privacy_banner_acked = "2026-08-17T10:12:06Z"
